name: Labeling develop to release PR
on:
  pull_request:
    types: [ opened ]
    branches: [ release ]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check labels from PR title
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}