name: Release labeling

on:
  pull_request:
    types: [ opened ]
    branches:
      - develop

jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
      - uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

