name: Release labeling
on:
  pull_request_target:
    types: [ opened ]
    branches:
      - release
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

