# This yml file used for release dns_lib.aar when release branch detect push or pull_request event.
name: Release dns_lib aar

on:
  pull_request:
    branches: [ release ]
    types: [ closed ]
jobs:
  release_dns_lib:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'release'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Extract dns_lib-debug.aar with Gradle
        run: ./gradlew dns_lib:assembleDebug
      - name: Extract dns_lib-release.aar with Gradle
        run: ./gradlew dns_lib:assembleRelease
      - name: Upload dns_lib-debug.aar & dns_lib-release.aar artifact
        uses: actions/upload-artifact@v3
        with:
          name: dns_lib aar files
          path: dns_lib/build/outputs/aar/
      - name: Upload to remote storage release branch
        run: |
          git add 'dns_lib/build/outputs/aar/'
          git config --global user.email '2022dontsleep@gmail.com'
          git config --global user.name 'DontSleep2022'
          git commit -m 'Upload dns_lib aar'
          git push
      - name: Create release note
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-config-dns_lib.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}